package com.example.plantasdemam

data class Planta(
    val id: Int,
    val nombreComun: String,
    val nombreCientifico: String,
    val categoria: String,
    val descripcion: String,
    val beneficios: List<String>,
    val formaDeUso: String,
    val contraindicaciones: String,
    val imagenNombre: String,
    val videoId: String = "jNQXAC9IVRw",
    var esFavorita: Boolean = false
)

val plantasData = listOf(
    Planta(1, "Manzanilla", "Matricaria chamomilla", "Relajante",
        "La manzanilla es una de las hierbas medicinales más antiguas.",
        listOf("Calma la digestión", "Anti-inflamatoria", "Reduce la ansiedad"),
        "Infusión de flores secas 10 minutos.",
        "Evitar durante el embarazo.",
        "manzanilla", "iltax_1_SVM"),
    Planta(2, "Lavanda", "Lavandula angustifolia", "Relajante",
        "La lavanda es conocida por su aroma relajante.",
        listOf("Reduce el estrés", "Mejora el sueño", "Alivia dolores de cabeza"),
        "Aromaterapia o infusión suave.",
        "No ingerir aceite esencial puro.",
        "lavanda", "0_dwmDHSdZo"),
    Planta(3, "Equinácea", "Echinacea purpurea", "Inmune",
        "Valorada por fortalecer el sistema inmunológico.",
        listOf("Fortalece el sistema inmunológico", "Reduce resfriados", "Antiinflamatoria"),
        "Cápsula o té máximo 2 semanas.",
        "No usar en enfermedades autoinmunes.",
        "echinacea", "xh2_EE6cQss"),
    Planta(4, "Jengibre", "Zingiber officinale", "Antiinflamatorio",
        "Raíz con miles de años de uso medicinal.",
        listOf("Antiinflamatorio natural", "Mejora la circulación", "Alivia náuseas"),
        "Té con 1 rodaja fresca 5 minutos.",
        "Cautela con gastritis o úlceras.",
        "jengibre", "f6t8h6owauo"),
    Planta(5, "Aloe Vera", "Aloe barbadensis miller", "Digestivo",
        "Planta suculenta con propiedades extraordinarias.",
        listOf("Cicatriza la piel", "Mejora la digestión", "Antibacteriana"),
        "Gel directo o 2 cucharadas en ayunas.",
        "No consumir la parte amarilla.",
        "aloe_vera", "PmkTIhja9M4"),
    Planta(6, "Valeriana", "Valeriana officinalis", "Relajante",
        "Conocida por sus propiedades sedantes.",
        listOf("Combate el insomnio", "Reduce la ansiedad", "Relaja músculos"),
        "Infusión 30 minutos antes de dormir.",
        "No combinar con alcohol.",
        "valeriana", "sJsLMM5G59k"),
    Planta(7, "Menta", "Mentha piperita", "Digestivo",
        "Hierba aromática refrescante.",
        listOf("Alivia el estómago", "Refresca el aliento", "Alivia dolores de cabeza"),
        "Infusión de hojas frescas o secas.",
        "Evitar en personas con reflujo severo.",
        "menta", "l3MmQNwGF-s"),
    Planta(8, "Romero", "Rosmarinus officinalis", "Antiinflamatorio",
        "Arbusto mediterráneo rico en antioxidantes.",
        listOf("Mejora la memoria", "Estimula la circulación", "Antioxidante"),
        "Infusión de ramitas frescas.",
        "Evitar dosis altas en embarazo.",
        "romero", "Q8VmAyWlqMU"),
    Planta(9, "Árnica", "Arnica montana", "Antiinflamatorio",
        "Valorada por propiedades antiinflamatorias.",
        listOf("Reduce inflamación", "Alivia dolores musculares", "Acelera recuperación"),
        "Aplicar crema en zona afectada.",
        "USO EXTERNO SOLAMENTE.",
        "arnica", "Z1bUAzoG7cU"),
    Planta(10, "Tomillo", "Thymus vulgaris", "Inmune",
        "Propiedades antisépticas y expectorantes.",
        listOf("Alivia la tos", "Antibacteriano", "Fortalece el sistema inmunológico"),
        "Infusión con miel para la tos.",
        "Evitar dosis altas en embarazo.",
        "tomillo", "BPJSQ7eObuQ")
)